import type { Metadata } from "next";
import { Poppins, Crimson_Pro } from "next/font/google";
import "@/app/globals.css";
import Navigation from "@/app/components/navigation";

/* const poppins = Poppins({weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]})

const crimson = Crimson_Pro({weight: ["200", "300", "400", "500", "600", "700", "800", "900"]}) */

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`crimson antialiased`}
      >
        <Navigation />
        {children}
      </body>
    </html>
  );
}
